config/routes.rb
Rails.application.routes.draw do
  resources :alerts do
    collection { post :import}
  end
  get 'home/index'
  root :to => "alerts#index"

end

app/models/alert.rb
class Alert < ActiveRecord::Base


  mount_uploader :excel, ExcelUploader

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      alert = Alert.create! row.to_hash
      alert.save!
    end
  end

  #Working with Savon
  # Should I create a new model to send alert message? Text below establishes
  # connection w/ Stagin in GSI
  # client = Savon.client(wsdl: "https://staging.gsihealth.com:8083/NotificationManager-1.0/NotificationConsumer?wsdl")
  # <Savon::Client:0x000001040d5840 @globals=#<Savon::GlobalOptions:0x000001040d5818 
  # @option_type=:global, @options={:encoding=>"UTF-8", :soap_version=>1, 
  # :namespaces=>{}, :logger=>#<Logger:0x000001040d5778 @progname=nil, 
  # @level=0, @default_formatter=#<Logger::Formatter:0x000001040d56d8 
  # @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x000001040d5688 @shift_size=nil, 
  # @shift_age=nil, @filename=nil, @dev=#<IO:/dev/null>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x000001040d5638 
  # @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x000001040d55e8>>>>, 
  # :log=>true, :filters=>[], :pretty_print_xml=>false, :raise_errors=>true, 
  # :strip_namespaces=>true, :convert_response_tags_to=>
  # <Proc:0x000001040d5548@/usr/local/rvm/gems/ruby-2.0.0-p353/gems/savon-2.3.3/lib/savon/options.rb:56 (lambda)>, 
  # :multipart=>false, :wsdl=>"https://staging.gsihealth.com:8083/NotificationManager-1.0/NotificationConsumer?wsdl"}>, 
  # @wsdl=#<Wasabi::Document:0x000001040d5160 @document="https://staging.gsihealth.com:8083/NotificationManager-1.0/NotificationConsumer?wsdl", 
  # @request=#<HTTPI::Request:0x000001040d5070>>> asdfasdf



  #Go back to the railscast
  #Above worked just to import CSV
  #how am i going to send this stuff
  #Testing new import method below
  # def self.import(file)
  #   spreadsheet = open_spreadsheet(file)
  #   header = spreadsheet.row(1)
  #   (2..spreadsheet.last_row).each do |i|
  #       row = Hash[[header, spreadsheet.row(i)].transpose]
  #       product = find_by_id(row["id"]) || new
  #       product.attributes = row.to_hash.slice(*accessible_attributes)
  #       product.save!
  #   end
  # end

  # def self.open_spreadsheet(file)
  #   case File.extname(file.original_filename)
  #   when ".csv" then Csv.new(file.path, nil, :ignore)
  #   when ".xls" then Excel.new(file.path, nil, :ignore)
  #   when ".xlsx" then Excelx.new(file.path, nil, :ignore)
  #   else raise "Unknown file type: #{file.original_filename}"
  #   end
  # end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Alert.import(params[:file])
    redirect_to root_url, notice: "Alerts Imported"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:first_name, :last_name, :dob, :medicaid_id, :alert)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_field :dob %>
  </div>
  <div class="field">
    <%= f.label :medicaid_id %><br>
    <%= f.text_field :medicaid_id %>
  </div>
  <div class="field">
    <%= f.label :alert %><br>
    <%= f.text_area :alert %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
  <div>
  <%= link_to "Upload Alert", new_alert_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h1>Listing alerts</h1>
<!-- <div class="CSSTableGenerator" > -->
<div class="CSSTableGenerator">
  <table>
    
      
        <th>First Name</th>
        <th>Last Name</th>
        <th>DOB</th>
        <th>Medicaid ID</th>
        <th>Alert</th>
        <th colspan="3"></th>
      
    

    <tbody>
      <% @alerts.each do |alert| %>
        <tr>
          <td><%= alert.first_name %></td>
          <td><%= alert.last_name %></td>
          <td><%= alert.dob %></td>
          <td><%= alert.medicaid_id %></td>
          <td><%= alert.alert %></td>
          <!--<td><%= link_to 'Show', alert %></td> -->
          <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
          <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Create New Alert', new_alert_path %>
<br>
<br>
<br>

<%= form_tag import_alerts_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Submit" %>
<% end %>

<!-- <h2>Import Products</h2>

<%#= form_tag import_alerts_path, multipart: true do %>
  <%#= file_field_tag :file %>
  <%#= submit_tag "Import" %>
<%# end %>
 -->

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'New Alert', new_alert_path %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @alert.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @alert.last_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @alert.dob %>
</p>

<p>
  <strong>Medicaid:</strong>
  <%= @alert.medicaid_id %>
</p>

<p>
  <strong>Alert:</strong>
  <%= @alert.alert %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<h3>UI to upload excel doc to rails app</h3>

<%= form_tag import_alerts_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Submit" %>
<%= end %>

<!-- <h2>Import Products</h2>

<%#= form_tag import_products_path, multipart: true do %>
  <%#= file_field_tag :file %>
  <%#= submit_tag "Import" %>
<%# end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>McoAlertsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>